[colors.cursor]
cursor = "0xFFFFFF"
text = "0x000000"

[terminal.shell]
args = [
  "-ic",
  "echo; fastfetch; exec bash"
]
program = "/usr/bin/bash"

[window]
opacity = 0.5

[font.normal]
family = "Ubuntu Mono"
style = "Regular"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"


[[hints.enabled]]
regex = "[^ ]+\\.rs:\\d+:\\d+"

  [hints.enabled.command]
  program = "code"
  args = [ "--goto" ]

  [hints.enabled.mouse]
  enabled = true

[env]
TERM = "xterm-256color"

